/** Declaration file generated by dts-gen */

export function basic(options: any, checker: any): any;

export function connect(auth: any): any;

export function digest(options: any, checker: any): any;

export function hapi(): any;

export function koa(auth: any): any;

export function passport(auth: any): any;

